### ISSUE TITLE
raco fails with "package is already installed"

### ISSUE THREAD

**Issue by ulysses4ever** [Bogdanp/setup-racket-cache-example#1]
Here's our failing job: https://github.com/nuprl/website/runs/4060978881

We have the following incantation in `.github/workflows`:
```
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Racket dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/racket
            ~/.local/share/racket
          key: default
      - name: Install Racket
        uses: Bogdanp/setup-racket@v0.8
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '7.9'
          packages: 'gregor,frog,honu'
```

Is caching supposed to work in the presence of `raco`-packages?

**Comment by Bogdanp** [comment]
I would recommend removing the `packages: ...` line and adding an explicit step to install the dependencies. For example:

```
      ...
      - name: Install Racket
        uses: Bogdanp/setup-racket@v0.8
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '7.9'
      - name: Install Dependencies
        run: raco pkg install --auto --skip-installed gregor frog honu
```

The trick here is to pass the `--skip-installed` flag to `raco pkg install`, which the `packages: ...` syntax doesn't know how to do.

Also, I would recommend upgrading to the latest version of setup-racket (1.6.1).
